#!/usr/bin/env python3
"""Generate the compose override that mounts every project into the services.

``projects.json`` (repo root, not committed) lists the projects the input
processor serves. The container only ever sees ``/projects/<name>/{inputs,
preprocessed,cache}``, so the host paths in that file have to be turned into
volume mounts. That is what this script does: it validates ``projects.json``,
creates the output folders, and writes ``docker-compose.override.yaml``, which
compose picks up automatically.

    python scripts/sync_projects.py
    docker compose up -d

Only the standard library is used, because this runs on the host, not in the
image. The container-side counterpart of this file is
``input-processor/src/projects/model.py``: the two must agree on the project
name rule and on the ``inputs``/``preprocessed``/``cache`` layout.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Optional, Sequence

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG = REPO_ROOT / "projects.json"
DEFAULT_OUTPUT = REPO_ROOT / "docker-compose.override.yaml"
DEFAULT_COMPOSE = REPO_ROOT / "docker-compose.yaml"

EXAMPLE_CONFIG = "projects.example.json"
OVERRIDE_HEADER = "Generated by scripts/sync_projects.py -- edit projects.json instead."

PROJECTS_ROOT = "/projects"
CONFIG_MOUNT = "/config/projects.json"
DATA_DIRNAME = ".spec2test-data"
SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9._-]*$")
SERVICES = ("input-processor",)

INPUTS = "inputs"
PREPROCESSED = "preprocessed"
CACHE = "cache"


class ConfigError(RuntimeError):
    """Raised when projects.json is missing, malformed or inconsistent."""


@dataclass(frozen=True)
class Project:
    """One project, with host paths already resolved."""

    name: str
    inputs: Path
    preprocessed: Path
    cache: Path

    def mounts(self) -> tuple[str, ...]:
        """The three volume mounts of this project, in container terms."""
        return (
            f"{self.inputs}:{PROJECTS_ROOT}/{self.name}/{INPUTS}:ro",
            f"{self.preprocessed}:{PROJECTS_ROOT}/{self.name}/{PREPROCESSED}",
            f"{self.cache}:{PROJECTS_ROOT}/{self.name}/{CACHE}",
        )


def load_config(config_path: Path) -> list[Project]:
    """Read ``projects.json`` and return its projects with resolved paths."""
    config_path = Path(config_path)
    if not config_path.is_file():
        raise ConfigError(
            f"{config_path} not found. Copy {EXAMPLE_CONFIG} to projects.json and "
            "list your projects there."
        )

    try:
        raw = json.loads(config_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ConfigError(f"{config_path} is not valid JSON: {exc}") from exc

    if not isinstance(raw, Mapping):
        raise ConfigError(f"{config_path} must contain a JSON object.")

    entries = raw.get("projects")
    if not isinstance(entries, list) or not entries:
        raise ConfigError(
            f"{config_path} must define a non-empty 'projects' list. "
            f"See {EXAMPLE_CONFIG}."
        )

    base = config_path.parent
    projects = [_project(entry, base) for entry in entries]
    _reject_duplicates(projects)
    return projects


def _project(entry: Any, base: Path) -> Project:
    if not isinstance(entry, Mapping):
        raise ConfigError(f"Each project entry must be an object, got {type(entry).__name__}.")

    name = str(entry.get("name", "")).strip()
    if not SLUG_RE.match(name):
        raise ConfigError(
            f"Invalid project name {name!r}. Use lowercase letters, digits, dots, "
            "dashes or underscores, starting with a letter or digit."
        )

    fallback = base / DATA_DIRNAME / name
    return Project(
        name=name,
        inputs=_resolve(entry, INPUTS, base / name / INPUTS, base),
        preprocessed=_resolve(entry, PREPROCESSED, fallback / PREPROCESSED, base),
        cache=_resolve(entry, CACHE, fallback / CACHE, base),
    )


def _resolve(entry: Mapping[str, Any], key: str, default: Path, base: Path) -> Path:
    raw = str(entry.get(key, "") or "").strip()
    path = Path(raw).expanduser() if raw else default
    if not path.is_absolute():
        path = base / path
    return path.resolve()


def _reject_duplicates(projects: Iterable[Project]) -> None:
    seen: set[str] = set()
    for project in projects:
        if project.name in seen:
            raise ConfigError(f"Project '{project.name}' is defined twice.")
        seen.add(project.name)


def check_paths(projects: Sequence[Project]) -> None:
    """Fail with one message listing everything that is wrong."""
    problems = [
        f"  - project '{project.name}': inputs {project.inputs} does not exist"
        for project in projects
        if not project.inputs.is_dir()
    ]
    if problems:
        raise ConfigError(
            "The following inputs folders are missing:\n"
            + "\n".join(problems)
            + "\nCreate them, or fix the paths in projects.json."
        )


def create_output_folders(projects: Sequence[Project]) -> None:
    """Make sure the preprocessed/ and cache/ folders exist on the host."""
    for project in projects:
        project.preprocessed.mkdir(parents=True, exist_ok=True)
        project.cache.mkdir(parents=True, exist_ok=True)


def configured_services(compose_path: Path) -> tuple[str, ...]:
    """The services the override may touch.

    A project folder is handed to the services that need it (``SERVICES``) and
    to no others, and only when the base compose file defines them: an override
    must never introduce a service the base one does not have. Read with a
    simple scan instead of a YAML parser — the base file is ours.
    """
    compose_path = Path(compose_path)
    if not compose_path.is_file():
        return SERVICES

    found: list[str] = []
    inside_services = False
    for line in compose_path.read_text(encoding="utf-8").splitlines():
        if line.startswith("services:"):
            inside_services = True
            continue
        if not inside_services:
            continue
        if line and not line[0].isspace():
            break  # a new top-level key ends the services block
        match = re.match(r"^ {2}([A-Za-z0-9._-]+):\s*$", line)
        if match:
            found.append(match.group(1))

    return tuple(name for name in found if name in SERVICES)


def render_override(
    projects: Sequence[Project],
    config_path: Path,
    services: Sequence[str] = SERVICES,
) -> str:
    """Return the YAML text of the compose override."""
    lines = [
        f"# {OVERRIDE_HEADER}",
        "# Re-run 'python scripts/sync_projects.py' after editing projects.json.",
        "services:",
    ]
    for service in services:
        lines.append(f"  {service}:")
        lines.append("    volumes:")
        for project in projects:
            lines.extend(f'      - "{mount}"' for mount in project.mounts())
        lines.append(f'      - "{Path(config_path).resolve()}:{CONFIG_MOUNT}:ro"')
    return "\n".join(lines) + "\n"


def write_override(output_path: Path, content: str) -> None:
    Path(output_path).write_text(content, encoding="utf-8")


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--compose", type=Path, default=DEFAULT_COMPOSE)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate projects.json and report what would change, without writing",
    )
    parser.add_argument("--quiet", action="store_true", help="only report errors")
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    try:
        projects = load_config(args.config)
        check_paths(projects)
    except ConfigError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    services = configured_services(args.compose)
    if not services:
        print(
            f"error: {args.compose} defines none of the services that need the "
            f"project folders ({', '.join(SERVICES)}).",
            file=sys.stderr,
        )
        return 1

    override = render_override(projects, args.config, services)

    if args.check:
        _report(projects, services, args, written=False)
        return 0

    create_output_folders(projects)
    write_override(args.output, override)
    if not args.quiet:
        _report(projects, services, args, written=True)
    return 0


def _report(projects: Sequence[Project], services: Sequence[str], args: argparse.Namespace, *, written: bool) -> None:
    verb = "Wrote" if written else "Would write"
    print(f"{verb} {args.output} for {len(projects)} project(s):")
    for project in projects:
        print(f"  - {project.name}: {project.inputs}")
    print(f"  mounted into: {', '.join(services)}")
    if written:
        print("Next: docker compose up -d")


if __name__ == "__main__":
    raise SystemExit(main())
