#!/usr/bin/env python3
"""Indice portable de requisitos, sin depender de plataformas externas ni librerias."""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import project_config as pc  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
MESSAGES = {
    "es": {
        "title": "# ÍNDICE DE ÉPICAS — {project}",
        "generated": "<!-- Generado por scripts/idx.py -->",
        "scenarios": "escenarios",
        "total": "Total: {epics} épicas · {features} features · {scenarios} escenarios",
        "diagnostics": "## Diagnóstico",
        "missing_features": "{epic}: features ausentes {numbers}",
        "missing_scenarios": "{feature}: escenarios ausentes {numbers}",
        "missing_epics": "Épicas ausentes: {ids}",
        "duplicates": "IDs duplicados: {ids}",
        "written": "Indice generado: {path}",
        "current": "Indice al dia: {path}",
        "stale": "Indice desactualizado: {path}. Ejecuta idx.py build",
        "by_state": "### Por estado",
        "by_feature": "### Por feature",
        "feature": "Feature",
        "unconfigured": "Sin estado configurado",
        "not_found": "{identifier}: no encontrado en {path}",
        "version": "Versión instalada: {value}",
        "commit": "Commit de origen: {value}",
        "commits_behind": "Commits detrás del kit: {count}",
        "comparison_unavailable": "Comparación con el kit no disponible: {reason}",
        "invalid_kit": "la ruta no es un clon de ProjectTraceKit",
        "unknown_commit": "commit de origen desconocido",
        "unrelated_commit": "el commit de origen no pertenece al historial del kit",
        "git_failure": "git rev-list falló",
        "git_unavailable": "git no está disponible",
    },
    "en": {
        "title": "# EPIC INDEX — {project}",
        "generated": "<!-- Generated by scripts/idx.py -->",
        "scenarios": "scenarios",
        "total": "Total: {epics} epics · {features} features · {scenarios} scenarios",
        "diagnostics": "## Diagnostics",
        "missing_features": "{epic}: missing features {numbers}",
        "missing_scenarios": "{feature}: missing scenarios {numbers}",
        "missing_epics": "Missing epics: {ids}",
        "duplicates": "Duplicate IDs: {ids}",
        "written": "Index generated: {path}",
        "current": "Index up to date: {path}",
        "stale": "Index out of date: {path}. Run idx.py build",
        "by_state": "### By status",
        "by_feature": "### By feature",
        "feature": "Feature",
        "unconfigured": "Unconfigured status",
        "not_found": "{identifier}: not found in {path}",
        "version": "Installed version: {value}",
        "commit": "Source commit: {value}",
        "commits_behind": "Commits behind the kit: {count}",
        "comparison_unavailable": "Kit comparison unavailable: {reason}",
        "invalid_kit": "path is not a ProjectTraceKit checkout",
        "unknown_commit": "source commit unknown",
        "unrelated_commit": "source commit is not in kit history",
        "git_failure": "git rev-list failed",
        "git_unavailable": "git unavailable",
    },
}


def load():
    try:
        config = pc.load_config(ROOT)
        pc.validate_contained_paths(config)
        pc.identifiers(config)
    except pc.ConfigError as error:
        raise SystemExit(f"Configuracion no valida: {error}") from error
    return config


def messages(config):
    return MESSAGES[pc.language(config) or "es"]


def project_name(config):
    default = "Proyecto" if (pc.language(config) or "es") == "es" else "Project"
    name = pc.get_str(config, "project.name").strip()
    return default if pc.is_unresolved(name, config) else name


def epic_files(config):
    # Listado y orden compartidos con consolidate-epics.py (project_config.epic_files).
    return pc.epic_files(pc.epics_root(ROOT, config), config)


def unknown_epic_id(config):
    return f"{pc.identifiers(config).epic_prefix}-?"


def epic_data(path, config=None):
    """Devuelve (epic_id, titulo, [(feature_id, titulo, [(escenario, estado)])]).

    Solo cuenta filas de la tabla de escenarios de cada feature; las tablas
    de comentarios, tasks y E2E repiten el mismo ID y no son escenarios nuevos.
    Los prefijos salen de ``identifiers.*.prefix``.
    """
    ids = pc.identifiers(config)
    feature_heading = re.compile(rf"^##\s+{ids.feature_numbers}\b\s*:?\s*(.*)$", re.IGNORECASE)
    scenario_row = re.compile(rf"^\|\s*{ids.scenario_numbers}\s*\|", re.IGNORECASE)
    lines = pc.read_text(path).splitlines()
    epic_match = re.match(rf"^#\s+{ids.epic_numbers}\b\s*:?\s*(.*)$", lines[0], re.IGNORECASE) if lines else None
    epic_id = ids.epic_id(epic_match.group(1)) if epic_match else unknown_epic_id(config)
    epic_title = (epic_match.group(2).strip() if epic_match else (lines[0].lstrip("# ").strip() if lines else path.stem))
    features = []
    current = None
    in_scenarios = False
    for line in lines:
        feature_match = feature_heading.match(line)
        if feature_match:
            current = (ids.feature_id(feature_match.group(1), feature_match.group(2)), feature_match.group(3).strip(), {})
            features.append(current)
            in_scenarios = False
            continue
        if line.startswith("## "):
            current = None
            in_scenarios = False
            continue
        if pc.SCENARIOS_HEADING.match(line):
            in_scenarios = True
            continue
        if line.startswith("### "):
            in_scenarios = False
            continue
        if current is None or not in_scenarios:
            continue
        row = scenario_row.match(line)
        if not row:
            continue
        scenario_id = ids.scenario_id(row.group(1), row.group(2), row.group(3))
        cells = pc.split_table_row(line)
        current[2].setdefault(scenario_id, cells[3] if len(cells) >= 4 else "")
    result = []
    for feature_id, title, scenarios in features:
        ordered = sorted(scenarios.items(), key=lambda item: tuple(int(part) for part in item[0].split("-")[1:]))
        result.append((feature_id, title, ordered))
    return epic_id, epic_title, result


def stats(config):
    text = messages(config)
    states = [str(state) for state in pc.get_list(config, "specification.states")]
    totals = dict.fromkeys(states, 0)
    unconfigured = 0
    rows = []
    for path in epic_files(config):
        _, _, features = epic_data(path, config)
        for feature_id, _, scenarios in features:
            counts = dict.fromkeys(states, 0)
            other = 0
            for _, state in scenarios:
                if state in counts:
                    counts[state] += 1
                    totals[state] += 1
                else:
                    other += 1
                    unconfigured += 1
            rows.append((feature_id, len(scenarios), counts, other))
    columns = states + ([text["unconfigured"]] if unconfigured else [])
    print(text["by_state"] + "\n")
    for state in states:
        print(f"- **{state}:** {totals[state]} {text['scenarios']}")
    if unconfigured:
        print(f"- **{text['unconfigured']}:** {unconfigured} {text['scenarios']}")
    total = sum(totals.values()) + unconfigured
    print(f"\n**Total:** {total} {text['scenarios']}\n")
    print(text["by_feature"] + "\n")
    print(f"| {text['feature']} | Total | " + " | ".join(columns) + " |")
    print("|---|---|" + "|".join(["---"] * len(columns)) + "|")
    for feature_id, count, counts, other in rows:
        values = [str(counts[state]) for state in states] + ([str(other)] if unconfigured else [])
        print(f"| {feature_id} | {count} | " + " | ".join(values) + " |")
    values = [f"**{totals[state]}**" for state in states] + ([f"**{unconfigured}**"] if unconfigured else [])
    print(f"| **TOTAL** | **{total}** | " + " | ".join(values) + " |")
    return 0


def find(config, identifier):
    found = False
    # Limites de palabra: EPIC-1 no coincide con EPIC-10 ni con EPIC-1-2.
    pattern = re.compile(rf"(?<!\w){re.escape(identifier.strip())}(?!\w|-\d)", re.IGNORECASE)
    for path in epic_files(config):
        for number, line in enumerate(pc.read_text(path).splitlines(), 1):
            if pattern.search(line):
                print(f"{path.name}:{number}: {line.strip()}")
                found = True
    if not found:
        print(messages(config)["not_found"].format(identifier=identifier, path=pc.epics_root(ROOT, config)))
        return 1
    return 0


def version(config, kit=None):
    text = messages(config)
    source_commit = pc.get_str(config, "template.source_commit").strip()
    print(text["version"].format(value=pc.get_str(config, "template.version").strip() or "unknown"))
    print(text["commit"].format(value=source_commit or "unknown"))
    kit = kit or (ROOT if (ROOT / "scripts" / "install-template.py").is_file() else None)
    if kit is None:
        return
    if not (kit / "scripts" / "install-template.py").is_file() or not (kit / "package.json").is_file():
        print(text["comparison_unavailable"].format(reason=text["invalid_kit"]))
        return
    if not source_commit or source_commit.casefold() == "unknown":
        print(text["comparison_unavailable"].format(reason=text["unknown_commit"]))
        return
    try:
        ancestry = subprocess.run(
            ["git", "-C", str(kit), "merge-base", "--is-ancestor", source_commit, "HEAD"],
            capture_output=True, text=True, check=False,
        )
        if ancestry.returncode != 0:
            print(text["comparison_unavailable"].format(reason=text["unrelated_commit"]))
            return
        count = subprocess.run(
            ["git", "-C", str(kit), "rev-list", "--count", f"{source_commit}..HEAD"],
            capture_output=True, text=True, check=False,
        )
        if count.returncode != 0:
            print(text["comparison_unavailable"].format(reason=text["git_failure"]))
        else:
            print(text["commits_behind"].format(count=count.stdout.strip()))
    except OSError:
        print(text["comparison_unavailable"].format(reason=text["git_unavailable"]))


def missing_numbers(numbers):
    return sorted(set(range(1, max(numbers) + 1)) - set(numbers)) if numbers else []


def build(config, check=False):
    text = messages(config)
    index = pc.requirements_root(ROOT, config) / pc.requirements_file_relative(Path("epics/index.md"), config)
    files = epic_files(config)
    seen_ids = set()
    duplicate_ids = []
    diagnostics = []
    epic_numbers = []
    total_features = 0
    total_scenarios = 0
    lines = [text["title"].format(project=project_name(config)), "", text["generated"], ""]
    for path in files:
        epic_id, epic_title, features = epic_data(path, config)
        if epic_id != unknown_epic_id(config):
            epic_numbers.append(int(epic_id.split("-")[1]))
        identifiers = [epic_id] + [feature_id for feature_id, _, _ in features]
        identifiers += [scenario for _, _, scenarios in features for scenario, _ in scenarios]
        for identifier in identifiers:
            if identifier in seen_ids:
                duplicate_ids.append(identifier)
            seen_ids.add(identifier)
        total_features += len(features)
        total_scenarios += sum(len(scenarios) for _, _, scenarios in features)
        missing = missing_numbers([int(feature_id.split("-")[2]) for feature_id, _, _ in features])
        if missing:
            diagnostics.append(text["missing_features"].format(epic=epic_id, numbers=", ".join(map(str, missing))))
        for feature_id, _, scenarios in features:
            missing = missing_numbers([int(scenario.split("-")[3]) for scenario, _ in scenarios])
            if missing:
                diagnostics.append(
                    text["missing_scenarios"].format(feature=feature_id, numbers=", ".join(map(str, missing)))
                )
        # relpath funciona aunque el indice no sea ancestro de la carpeta de epicas.
        relative_path = Path(os.path.relpath(path, index.parent)).as_posix()
        lines.append(f"- [{path.stem}]({relative_path}) — **{epic_id}**: {epic_title}")
        for feature_id, feature_title, scenarios in features:
            lines.append(f"  - **{feature_id}**: {feature_title} ({len(scenarios)} {text['scenarios']})")
            for scenario, _ in scenarios:
                lines.append(f"    - `{scenario}`")
    lines.extend(["", text["total"].format(epics=len(files), features=total_features, scenarios=total_scenarios)])
    missing_epics = missing_numbers(epic_numbers)
    if missing_epics:
        diagnostics.append(text["missing_epics"].format(ids=", ".join(pc.identifiers(config).epic_id(number) for number in missing_epics)))
    if duplicate_ids:
        diagnostics.append(text["duplicates"].format(ids=", ".join(sorted(set(duplicate_ids)))))
    if diagnostics:
        lines.extend(["", text["diagnostics"], "", *[f"- {diagnostic}" for diagnostic in diagnostics]])
    content = "\n".join(lines) + "\n"
    if check:
        # --check no escribe: falla si el indice versionado no coincide con el generado.
        if index.is_file() and pc.read_text(index) == content:
            print(text["current"].format(path=index))
            return 0
        print(text["stale"].format(path=index), file=sys.stderr)
        return 1
    index.parent.mkdir(parents=True, exist_ok=True)
    index.write_text(content, encoding="utf-8", newline="\n")
    print(text["written"].format(path=index))
    return 0


def main(argv=None):
    pc.configure_stdio()
    parser = argparse.ArgumentParser(description=__doc__)
    subcommands = parser.add_subparsers(dest="command", required=True)
    build_parser = subcommands.add_parser("build", help="Regenera el indice configurado en paths.requirements_index")
    build_parser.add_argument(
        "--check", action="store_true", help="No escribe; falla si el indice no esta al dia"
    )
    subcommands.add_parser("stats", help="Cuenta escenarios por estado configurado en specification.states")
    find_parser = subcommands.add_parser("find", help="Busca un identificador en las epicas")
    find_parser.add_argument("identifier")
    version_parser = subcommands.add_parser("version", help="Muestra la version instalada y compara con un clon del kit")
    version_parser.add_argument("--kit", type=Path, help="Ruta a un clon local de ProjectTraceKit para comparar commits")
    args = parser.parse_args(argv)
    config = load()
    if args.command == "build":
        return build(config, check=args.check)
    if args.command == "stats":
        return stats(config)
    if args.command == "version":
        version(config, kit=args.kit)
        return 0
    return find(config, args.identifier)


if __name__ == "__main__":
    sys.exit(main())
